In [2]:
#http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb
import numpy as np
numpy.__version__

'1.11.2'

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [11]:
L3 = ['string',4,True,3.1416]
[type(item) for item in L3]


[str, int, bool, float]

### Fixed Type Arrays in Python

In [15]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating NumPy Arrays

In [18]:
#integer arrays from lists
np.array([1,2,4,5,3])

array([1, 2, 4, 5, 3])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [19]:
np.array([1,3,4,2],dtype='float32')

array([ 1.,  3.,  4.,  2.], dtype=float32)

 here's one way of initializing a multidimensional array using a list of lists:

In [20]:
np.array([range(i,i+3) for i in (2,4,6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [21]:
#creating a length10 int array filled with 0s
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
#creating a 3x5 array filled with ones
np.ones((3,5),dtype='float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
#Creating a 3x5 array with value 3.14
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
#create an array of 5 values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [27]:
#Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[ 0.89704513,  0.19720958,  0.86543261],
       [ 0.4538841 ,  0.60252481,  0.42041194],
       [ 0.23111975,  0.50157007,  0.93279729]])

In [30]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.12488726,  0.36700153, -1.74082447],
       [-0.19850026, -1.24858946,  0.40244876],
       [-0.4497088 ,  1.65290868,  0.64030269]])

In [32]:
#3x3 array of random integers in interval [0,10)
np.random.randint(0,10,(3,3))

array([[4, 2, 5],
       [4, 5, 7],
       [3, 7, 4]])

In [33]:
#create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [34]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([ 1.,  1.,  1.])

# Basics of NumPy arrays

### NumPy array attributes

In [38]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [39]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x3 = np.random.randint(100,size=(3,5,4))
x3

array([[[46, 88, 81, 37],
        [25, 77, 72,  9],
        [20, 80, 69, 79],
        [47, 64, 82, 99],
        [88, 49, 29, 19]],

       [[19, 14, 39, 32],
        [65,  9, 57, 32],
        [31, 74, 23, 35],
        [75, 55, 28, 34],
        [ 0,  0, 36, 53]],

       [[ 5, 38, 17, 79],
        [ 4, 42, 58, 31],
        [ 1, 65, 41, 57],
        [35, 11, 46, 82],
        [91,  0, 14, 99]]])

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):


In [44]:
print("x3 ndim : ",x3.ndim)
print("x3 shape : ",x3.shape)
print("x3 size : ",x3.size)

x3 ndim :  3
x3 shape :  (3, 5, 4)
x3 size :  60


Data type of the array

In [46]:
print("x3 dtype : ",x3.dtype)

x3 dtype :  int64


Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array:

In [47]:
print("x3 itemsize : ",x3.itemsize)
print("x3 nbytes : ",x3.nbytes)

x3 itemsize :  8
x3 nbytes :  480


## Array Indexing : Accesing single Elements

In [48]:
x1

array([5, 0, 3, 3, 7, 9])

In [49]:
x1[0]

5

In [50]:
x1[4]

7

In [53]:
#Use -ve indices to index from the end of the array
x1[-1]
x1[-5]

0

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x2[0,0]

3

In [56]:
x2[1,2]

8

In [57]:
x2[-2,-2]

8

Values can also be modified using any of the above index notation:

In [59]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [60]:
x1[0] = 3.1416
x1[0]
#As we tried inserting an float into an integer array, the number was truncated and
#int was inserted

3

## Array Slicing: Accessing Subarrays
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### 1D Subarrays

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#First 5 elements
y1 = x[:5]
print(y1)
y2 = x[0:5:1]
print(y2)

[0 1 2 3 4]
[0 1 2 3 4]


In [70]:
#Elements after index 5
y3 = x[6:]
print(y3)
y4 = x[6:10:1]
print(y4)

[6 7 8 9]
[6 7 8 9]


In [72]:
#mid sub-array
x[4:7]

array([4, 5, 6])

In [75]:
#every second element
x[::2]

array([0, 2, 4, 6, 8])

In [76]:
#Every second element starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [77]:
#All elements reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [78]:
#every second element reversed, starting from index 5
x[5::-2]

array([5, 3, 1])

 ## Multidimensional Sub-arrays

In [79]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [81]:
#first 2 rows and 3 columns
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [90]:
#all rows, every alternate column
a1 = x2[:,::2]
a2 = x2[:3,::2]
print(a1)
print("")
print("a1 and a2 are 2 ways of getting the same output")
print("")
print(a2)

[[12  2]
 [ 7  8]
 [ 1  7]]

2 ways of getting the same output

[[12  2]
 [ 7  8]
 [ 1  7]]


In [92]:
x2[::-1,::-1] #rows and columns being flipped

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

####  Accessing single rows and columns

In [93]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [98]:
print(x2[:,0]) #first col of x2

[12  7  1]


In [96]:
#first row of x2
print(x2[0,:])
print(x2[0])

[12  5  2  4]
[12  5  2  4]


####  Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [99]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [101]:
#Extracting 2x2 array from this
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [102]:
#Modifying x2_sub
x2_sub[0,0] = 99

In [103]:
#change in original array
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

###  Copying Arrays

In [104]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [105]:
#Modifying sub array
x2_sub_copy[0,0] = 1000

In [107]:
x2 #no change in the original array

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### Reshaping of array

In [110]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
x= np.array([1,2,3])
x

array([1, 2, 3])

In [118]:
x.shape

(3,)

In [120]:
y = x.reshape(1,3)
y

array([[1, 2, 3]])

In [121]:
y.shape

(1, 3)

In [123]:
y1 = x[np.newaxis,:] #Another way of doing the above
y1

array([[1, 2, 3]])

In [124]:
y1.shape

(1, 3)

In [125]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [126]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

###  Array Concatenation and Splitting

##### Concatenation of arrays

In [127]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.concatenate([x,y])

array([ 1,  2,  3, 10, 20, 30])

In [128]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3, 10, 20, 30, 99, 99, 99])

In [132]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
#concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [134]:
#concatenate along the second axis
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [135]:
#For arrays of mixed dimensions
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [136]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

##### Splitting of Arrays

In [138]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [139]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [141]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions

In [142]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output    
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [143]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 1.8 s per loop


##  UFuncs

In [144]:
print(compute_reciprocals(values))
print(1/values)

[ 0.16666667  1.          0.25        0.25        0.125     ]
[ 0.16666667  1.          0.25        0.25        0.125     ]


In [145]:
%timeit (1.0/big_array)

The slowest run took 4.19 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 2.25 ms per loop


In [146]:
np.arange(5) / np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [148]:
x = np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [149]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [150]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2) #remainder

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [151]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [154]:
x = np.array([-2, -1, 0, 1, 2])

print(abs(x))
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]


###  Trigonometric Function

In [155]:
theta = np.linspace(0, np.pi, 3)

In [157]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [ 0.          1.57079633  3.14159265]
sin(theta) =  [  0.00000000e+00   1.00000000e+00   1.22464680e-16]
cos(theta) =  [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
tan(theta) =  [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [158]:
#Inverse trigonometric functions
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [ 3.14159265  1.57079633  0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and Logarithms

In [159]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [  2.71828183   7.3890561   20.08553692]
2^x   = [ 2.  4.  8.]
3^x   = [ 3  9 27]


In [160]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x)  = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]


For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

In [161]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


This can even be used with array views. For example, we can write the results of a computation to every other element of a specified array:

In [162]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


or very large arrays the memory savings from careful use of the out argument can be significant.

### Aggregates

In [165]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [164]:
np.multiply.reduce(x)

120

In [167]:
#If we'd like to store all the intermediate results of the computation, we can instead use accumulate:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

### Outer products

In [169]:
#We can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Aggregations - Summary Statistics

In [171]:
import numpy as np

L = np.random.random(100)
L

array([ 0.49555108,  0.9552979 ,  0.81778172,  0.49902653,  0.22465879,
        0.89005733,  0.30654364,  0.37441302,  0.75259926,  0.17746194,
        0.10144419,  0.9999925 ,  0.78050216,  0.06618773,  0.6336205 ,
        0.31063248,  0.94833285,  0.97968792,  0.24481674,  0.62413396,
        0.75772597,  0.56219826,  0.49924365,  0.41224358,  0.54175922,
        0.22209216,  0.45803492,  0.23090228,  0.74940011,  0.65656829,
        0.51324137,  0.67519693,  0.43960314,  0.1163365 ,  0.44355178,
        0.24505542,  0.64322067,  0.25284067,  0.95285657,  0.43699403,
        0.00529613,  0.1335414 ,  0.49690312,  0.18552615,  0.76678812,
        0.90262236,  0.19030507,  0.62148897,  0.03547253,  0.19481381,
        0.22263448,  0.04200446,  0.84306475,  0.02427196,  0.96734127,
        0.7920487 ,  0.13799814,  0.61435863,  0.33066993,  0.51691549,
        0.68283419,  0.69578837,  0.70090542,  0.01525615,  0.67596141,
        0.39643849,  0.08322081,  0.56234571,  0.68861915,  0.77

In [173]:
%timeit sum(L)

The slowest run took 5.02 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.7 µs per loop


In [174]:
%timeit np.sum(L)

The slowest run took 21.97 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.8 µs per loop


Hence sum in np is calculated much more quickly. Another example given below

In [176]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 97.1 ms per loop
1000 loops, best of 3: 443 µs per loop


### Minimum and Maximum

In [179]:
#Python default
%timeit min(big_array)
%timeit max(big_array)
print(min(big_array))
print(max(big_array))

10 loops, best of 3: 69.9 ms per loop
10 loops, best of 3: 69.7 ms per loop
2.0675143686e-07
0.999997425248


In [180]:
#Numpy
%timeit np.min(big_array)
%timeit np.max(big_array)
print(np.min(big_array))
print(np.max(big_array))

1000 loops, best of 3: 438 µs per loop
1000 loops, best of 3: 437 µs per loop
2.0675143686e-07
0.999997425248


For min, max, sum, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

### Multi Dimensional Aggregates


One common type of aggregation operation is an aggregate along a row or column. Say you have some data stored in a two-dimensional array:

In [183]:
M = np.random.random((3,4))
M

array([[ 0.71770264,  0.16798506,  0.78544208,  0.24538626],
       [ 0.44751074,  0.47445276,  0.54625186,  0.1002238 ],
       [ 0.18722235,  0.47416097,  0.53927062,  0.76289479]])