In [2]:
#http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb
import numpy as np
numpy.__version__

'1.11.2'

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [11]:
L3 = ['string',4,True,3.1416]
[type(item) for item in L3]


[str, int, bool, float]

### Fixed Type Arrays in Python

In [15]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating NumPy Arrays

In [18]:
#integer arrays from lists
np.array([1,2,4,5,3])

array([1, 2, 4, 5, 3])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [19]:
np.array([1,3,4,2],dtype='float32')

array([ 1.,  3.,  4.,  2.], dtype=float32)

 here's one way of initializing a multidimensional array using a list of lists:

In [20]:
np.array([range(i,i+3) for i in (2,4,6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [21]:
#creating a length10 int array filled with 0s
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
#creating a 3x5 array filled with ones
np.ones((3,5),dtype='float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
#Creating a 3x5 array with value 3.14
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
#create an array of 5 values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [27]:
#Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[ 0.89704513,  0.19720958,  0.86543261],
       [ 0.4538841 ,  0.60252481,  0.42041194],
       [ 0.23111975,  0.50157007,  0.93279729]])

In [30]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.12488726,  0.36700153, -1.74082447],
       [-0.19850026, -1.24858946,  0.40244876],
       [-0.4497088 ,  1.65290868,  0.64030269]])

In [32]:
#3x3 array of random integers in interval [0,10)
np.random.randint(0,10,(3,3))

array([[4, 2, 5],
       [4, 5, 7],
       [3, 7, 4]])

In [33]:
#create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [34]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([ 1.,  1.,  1.])

# Basics of NumPy arrays

### NumPy array attributes

In [38]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [39]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x3 = np.random.randint(100,size=(3,5,4))
x3

array([[[46, 88, 81, 37],
        [25, 77, 72,  9],
        [20, 80, 69, 79],
        [47, 64, 82, 99],
        [88, 49, 29, 19]],

       [[19, 14, 39, 32],
        [65,  9, 57, 32],
        [31, 74, 23, 35],
        [75, 55, 28, 34],
        [ 0,  0, 36, 53]],

       [[ 5, 38, 17, 79],
        [ 4, 42, 58, 31],
        [ 1, 65, 41, 57],
        [35, 11, 46, 82],
        [91,  0, 14, 99]]])

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):


In [44]:
print("x3 ndim : ",x3.ndim)
print("x3 shape : ",x3.shape)
print("x3 size : ",x3.size)

x3 ndim :  3
x3 shape :  (3, 5, 4)
x3 size :  60


Data type of the array

In [46]:
print("x3 dtype : ",x3.dtype)

x3 dtype :  int64


Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array:

In [47]:
print("x3 itemsize : ",x3.itemsize)
print("x3 nbytes : ",x3.nbytes)

x3 itemsize :  8
x3 nbytes :  480


## Array Indexing : Accesing single Elements

In [48]:
x1

array([5, 0, 3, 3, 7, 9])

In [49]:
x1[0]

5

In [50]:
x1[4]

7

In [53]:
#Use -ve indices to index from the end of the array
x1[-1]
x1[-5]

0

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x2[0,0]

3

In [56]:
x2[1,2]

8

In [57]:
x2[-2,-2]

8

Values can also be modified using any of the above index notation:

In [59]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [60]:
x1[0] = 3.1416
x1[0]
#As we tried inserting an float into an integer array, the number was truncated and
#int was inserted

3

## Array Slicing: Accessing Subarrays
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### 1D Subarrays

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#First 5 elements
y1 = x[:5]
print(y1)
y2 = x[0:5:1]
print(y2)

[0 1 2 3 4]
[0 1 2 3 4]


In [70]:
#Elements after index 5
y3 = x[6:]
print(y3)
y4 = x[6:10:1]
print(y4)

[6 7 8 9]
[6 7 8 9]


In [72]:
#mid sub-array
x[4:7]

array([4, 5, 6])

In [75]:
#every second element
x[::2]

array([0, 2, 4, 6, 8])

In [76]:
#Every second element starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [77]:
#All elements reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [78]:
#every second element reversed, starting from index 5
x[5::-2]

array([5, 3, 1])

 ## Multidimensional Sub-arrays

In [79]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [81]:
#first 2 rows and 3 columns
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [90]:
#all rows, every alternate column
a1 = x2[:,::2]
a2 = x2[:3,::2]
print(a1)
print("")
print("a1 and a2 are 2 ways of getting the same output")
print("")
print(a2)

[[12  2]
 [ 7  8]
 [ 1  7]]

2 ways of getting the same output

[[12  2]
 [ 7  8]
 [ 1  7]]


In [92]:
x2[::-1,::-1] #rows and columns being flipped

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

####  Accessing single rows and columns

In [93]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [98]:
print(x2[:,0]) #first col of x2

[12  7  1]


In [96]:
#first row of x2
print(x2[0,:])
print(x2[0])

[12  5  2  4]
[12  5  2  4]


####  Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [99]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [101]:
#Extracting 2x2 array from this
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [102]:
#Modifying x2_sub
x2_sub[0,0] = 99

In [103]:
#change in original array
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

###  Copying Arrays

In [104]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [105]:
#Modifying sub array
x2_sub_copy[0,0] = 1000

In [107]:
x2 #no change in the original array

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### Reshaping of array

In [110]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
x= np.array([1,2,3])
x

array([1, 2, 3])

In [118]:
x.shape

(3,)

In [120]:
y = x.reshape(1,3)
y

array([[1, 2, 3]])

In [121]:
y.shape

(1, 3)

In [123]:
y1 = x[np.newaxis,:] #Another way of doing the above
y1

array([[1, 2, 3]])

In [124]:
y1.shape

(1, 3)